#!/usr/bin/env python3
"""Regenerate study-plan/adaptive-schedule.md from current tracking state.

Reads:
  - tracking/{velocity-tracker,performance,domain-coverage,acronyms}.json
  - resources/objectives.yaml

Writes:
  - study-plan/adaptive-schedule.md  (deterministic, sort-key stable)

Idempotent. Safe to run after every session (and log-session.py can call it).
"""
from __future__ import annotations

import json
import sys
from datetime import date as date_cls
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
TRACKING = REPO_ROOT / "tracking"
RESOURCES = REPO_ROOT / "resources"
OUT = REPO_ROOT / "study-plan" / "adaptive-schedule.md"


def load_json(path: Path) -> dict:
    with path.open() as f:
        return json.load(f)


def main() -> int:
    velocity = load_json(TRACKING / "velocity-tracker.json")
    performance = load_json(TRACKING / "performance.json")
    coverage = load_json(TRACKING / "domain-coverage.json")
    acronyms = load_json(TRACKING / "acronyms.json")
    with (RESOURCES / "objectives.yaml").open() as f:
        objectives = yaml.safe_load(f)

    today = date_cls.today().isoformat()
    exam_date = velocity["examDate"]
    days_remaining = (
        date_cls.fromisoformat(exam_date) - date_cls.fromisoformat(today)
    ).days
    proj = velocity["projections"]

    lines: list[str] = []
    lines.append("# Adaptive Study Schedule")
    lines.append("")
    lines.append("_Auto-generated by `scripts/generate-schedule.py`. Do not edit by hand._")
    lines.append("")
    lines.append(f"- **Exam date:** {exam_date} ({days_remaining} days remaining)")
    lines.append(f"- **Sessions logged:** {velocity['sessions']}")
    if proj["readiness"] is not None:
        lines.append(
            f"- **Readiness:** {proj['readiness']:.0%}  "
            f"(coverage {proj['coverageAtExamDate']:.0%} × "
            f"7-day accuracy {proj['rolling7DayAccuracy']:.0%})"
        )
        lines.append(f"- **Risk:** {proj['riskLevel']}")
        lines.append(
            f"- **Recommended daily pace:** "
            f"{proj['recommendedDailyMinutes']} min, "
            f"{proj['recommendedQuestionsPerDay']} questions"
        )
    else:
        lines.append("- **Readiness:** not yet computed (no sessions)")
    lines.append("")

    lines.append("## Domain coverage")
    lines.append("")
    lines.append("| Domain | Weight | Topics studied | Quiz accuracy | Last studied |")
    lines.append("|---|---|---|---|---|")
    for domain_id in sorted(coverage["domains"]):
        d = coverage["domains"][domain_id]
        total = len(d["topicIds"])
        acc = f"{d['quizAccuracy']:.0%}" if d["quizAccuracy"] is not None else "—"
        last = d["lastStudied"] or "—"
        lines.append(
            f"| {domain_id} {d['name']} | {d['weight']:.0%} | "
            f"{d['topicsStudied']}/{total} | {acc} | {last} |"
        )
    lines.append("")

    weak_topics = [
        (tid, t)
        for tid, t in performance["topics"].items()
        if t["accuracy"] is not None and t["accuracy"] < 0.7
    ]
    weak_topics.sort(key=lambda x: (x[1]["accuracy"], -x[1]["questionsAnswered"]))
    lines.append("## Weakest topics (re-expose next session)")
    lines.append("")
    if weak_topics:
        lines.append("| Topic | Domain | Accuracy | Level | Confidence |")
        lines.append("|---|---|---|---|---|")
        for tid, t in weak_topics[:10]:
            lines.append(
                f"| {tid} {t['title']} | {t['domain']} | "
                f"{t['accuracy']:.0%} | L{t['level']} | {t['confidence']} |"
            )
    else:
        lines.append("_None yet — accuracy data accrues as sessions are logged._")
    lines.append("")

    untouched = [
        (tid, t)
        for tid, t in performance["topics"].items()
        if t["questionsAnswered"] == 0
    ]
    lines.append("## Untouched topics (priority for new study)")
    lines.append("")
    if untouched:
        by_domain: dict[str, list[tuple[str, dict]]] = {}
        for tid, t in untouched:
            by_domain.setdefault(t["domain"], []).append((tid, t))
        for domain_id in sorted(by_domain):
            d = coverage["domains"][domain_id]
            ids = sorted(by_domain[domain_id], key=lambda x: x[0])
            lines.append(f"- **{domain_id} {d['name']}** ({len(ids)} topics): " +
                         ", ".join(tid for tid, _ in ids[:8]) +
                         (" …" if len(ids) > 8 else ""))
    else:
        lines.append("_All topics touched at least once._")
    lines.append("")

    low_confidence_acronyms = [
        (term, info)
        for term, info in acronyms["acronyms"].items()
        if info["confidence"] in ("unknown", "low")
    ]
    low_confidence_acronyms.sort(key=lambda x: (-x[1]["timesSeen"], x[0]))
    lines.append("## Acronyms to review")
    lines.append("")
    if low_confidence_acronyms:
        lines.append("| Acronym | Expansion | Times seen | Confidence |")
        lines.append("|---|---|---|---|")
        for term, info in low_confidence_acronyms[:15]:
            lines.append(
                f"| {term} | {info.get('expansion', '—') or '—'} | "
                f"{info['timesSeen']} | {info['confidence']} |"
            )
    else:
        lines.append("_None flagged. Acronym tracking grows from `log-session.py` input._")
    lines.append("")

    lines.append("## Source material")
    lines.append("")
    lines.append(
        f"Quiz questions cite sections from "
        f"`{objectives['sourceRepo']}` "
        f"(submodule at `external/source-repo/`). "
        f"Per-section markdown lives under `resources/source-content/`."
    )
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
